"""Compatibility shim: the trend engine now lives in ``analysis``.

This module only re-exports names from ``analysis.numeric`` and
``analysis.trend`` so existing ``app.trend_engine`` imports keep working during
the shared-analysis migration. It contains no calculations, constants, or state
of its own and is deleted once every consumer imports from ``analysis``
directly.
"""

from analysis.numeric import (
    f32,
    float32_json,
    round_half_up,
    round_float32_half_up,
)
from analysis.trend import (
    AdvancedTrendWithVolume,
    Daily,
    DOWN,
    LONG_MA_PERIOD,
    MIN_DATA_REQUIRED,
    MOMENTUM_PERIOD,
    RSI_OVERBOUGHT,
    RSI_OVERSOLD,
    RSI_PERIOD,
    SHORT_MA_PERIOD,
    SIDEWAYS,
    UP,
    analyze_trend_with_volume,
    calc_atr,
    calc_average_dollar_volume,
    calc_confidence_with_volume,
    calc_ema,
    calc_macd,
    calc_macd_hist,
    calc_macd_signal,
    calc_momentum,
    calc_obv,
    calc_realized_volatility_expansion,
    calc_rsi,
    calc_sma,
    calc_trend_strength_with_volume,
    calc_volume_ma,
    calc_volume_momentum,
    calc_volume_ratio,
    calc_volume_roc,
    determine_direction_with_volume_and_macd,
    get_reversal_signals_with_volume,
    trend_strength_from_value,
)

__all__ = [
    "f32",
    "float32_json",
    "round_half_up",
    "round_float32_half_up",
    "AdvancedTrendWithVolume",
    "Daily",
    "DOWN",
    "LONG_MA_PERIOD",
    "MIN_DATA_REQUIRED",
    "MOMENTUM_PERIOD",
    "RSI_OVERBOUGHT",
    "RSI_OVERSOLD",
    "RSI_PERIOD",
    "SHORT_MA_PERIOD",
    "SIDEWAYS",
    "UP",
    "analyze_trend_with_volume",
    "calc_atr",
    "calc_average_dollar_volume",
    "calc_confidence_with_volume",
    "calc_ema",
    "calc_macd",
    "calc_macd_hist",
    "calc_macd_signal",
    "calc_momentum",
    "calc_obv",
    "calc_realized_volatility_expansion",
    "calc_rsi",
    "calc_sma",
    "calc_trend_strength_with_volume",
    "calc_volume_ma",
    "calc_volume_momentum",
    "calc_volume_ratio",
    "calc_volume_roc",
    "determine_direction_with_volume_and_macd",
    "get_reversal_signals_with_volume",
    "trend_strength_from_value",
]
